spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/eventostec
spring.datasource.username=postgres
spring.datasource.password=Infinity@5

aws.region=us-east-1
aws.bucket.name = teste-aula-projeto-eventostec-imagens